name = "my-app"
main = "src/index.ts"
compatibility_date = "2024-11-21"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "CACHE"
id = "3c2e7fd87aea4d189348344e7c1aa3e1"
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "cloudflare-pain-db"
# database_id = "8ba6aa3b-dae6-49fc-a749-1ae6c6050a84"
# migrations_dir = "drizzle"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1